name: docker publish arm64
on:
  push:
    tags:
      - '*'
jobs:
  build-arm64:
    runs-on: macos-14
    timeout-minutes: 360
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup docker on macOS
        uses: douglascamata/setup-docker-macos-action@v1-alpha
      - name: setup qemu
        uses: docker/setup-qemu-action@v3
      - name: setup buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: print available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: set version from tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: print version number
        run: echo ${{ env.RELEASE_VERSION }}
      - name: login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_UPLOAD_USERNAME }}
          password: ${{ secrets.DOCKER_UPLOAD_TOKEN }}
      - name: build & upload
        run: |
          docker buildx build \
          --push \
          --tag plattar/python-usd:version-${{ env.RELEASE_VERSION }}-arm64 \
          --platform linux/arm64 \
          --file Dockerfile .